apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitops-demo
  namespace: staging
  labels:
    app: gitops-demo
    env: staging
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gitops-demo
  template:
    metadata:
      labels:
        app: gitops-demo
        env: staging
    spec:
      containers:
        - name: gitops-demo
          image: whgustn28/gitops-demo:latest   # CI updates this line
          ports:
            - containerPort: 8000
          env:
            - name: ENV
              value: "staging"
            - name: APP_VERSION
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['app']
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
